name: bacalhau-expanso-cloud-single-region

x-common-env-variables: &common-env-variables
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  BACALHAU_DISABLEANALYTICS: true

x-compute-image: &compute-image
  image: ghcr.io/bacalhau-project/bacalhau:${COMPUTE_IMAGE_TAG:-latest-dind}

services:
  compute:
    <<: *compute-image
    command: serve -c /etc/bacalhau/config.yaml
    volumes:
      - ./config.yaml:/etc/bacalhau/config.yaml
    environment:
      <<: *common-env-variables
    depends_on:
      storage:
        condition: service_healthy
    deploy:
      replicas: 10
    privileged: true
    networks:
      - bacalhau-network

  storage:
    image: quay.io/minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/my-bucket && minio server /data --console-address ":9001"'
    environment: *common-env-variables
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      bacalhau-network:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

  client:
    image: ghcr.io/bacalhau-project/bacalhau:latest
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    stop_signal: SIGTERM
    stop_grace_period: 3s
    environment:
      <<: *common-env-variables
      BACALHAU_API_HOST: <YOUR_NETWORK_ID>.us1.cloud.expanso.io
    networks:
      - bacalhau-network

networks:
  bacalhau-network:
